// lib/articleReader.js - shared readers + normalizer for the /article reader and
// the /articles archive, plus the topic-draft -> article publish helpers.
//
// One normalizer returns a unified shape regardless of how a row stores its
// body. Three input cases:
//   1. plain-prose preview bodies      -> kind 'prose' (ReactMarkdown paragraphs)
//   2. legacy HTML essay bodies        -> kind 'raw'   (verbatim pass-through)
//   3. published topic-draft features  -> kind 'prose' (clean semantic h2/p)
// Cases 1 and 3 share the semantic render path; case 2 is self-contained markup
// (a-hero6 etc.) that must not be double-wrapped.

import { sql } from './db.js';

function readMinutes(body) {
  const words = (body || '').replace(/<[^>]+>/g, ' ').trim().split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 250));
}

// Byline / provenance. auto-generated previews and AI-draft features show a
// provenance treatment, not a human byline; human-authored pieces show "By X".
export function deriveByline(a) {
  if (a.author === 'auto') return { kind: 'auto', label: 'Generated by Sportsvyn', author: null };
  if (a.type === 'feature') return { kind: 'ai', label: 'Sportsvyn', note: 'AI draft, editor-reviewed', author: a.author || 'Sportsvyn' };
  return { kind: 'human', label: `By ${a.author}`, author: a.author };
}

// A body is legacy self-contained markup when the article is an essay whose body
// opens with an HTML tag (its own a-hero6 / a-fig styling). Everything else is
// semantic content the reader typography styles.
function isRawHtmlBody(a) {
  return a.type === 'essay' && /^\s*</.test(a.body || '');
}

export function normalizeArticle(a) {
  const raw = isRawHtmlBody(a);
  return {
    id: a.id,
    slug: a.slug,
    type: a.type,
    headline: a.title,
    dek: a.subtitle || null,
    kicker: [a.primary_tag_name, a.league_name].filter(Boolean).join(' · ') || null,
    kind: raw ? 'raw' : 'prose',
    rawHtml: raw ? a.body : null,
    body: raw ? null : (a.body || ''),
    byline: deriveByline(a),
    publishedAt: a.published_at,
    readMin: readMinutes(a.body),
  };
}

// Archive list. Published only, newest first, paginated (default 30/page).
export async function getPublishedArticles({ limit = 30, offset = 0 } = {}) {
  const rows = await sql`
    SELECT a.id, a.slug, a.title, a.subtitle, a.type, a.author, a.published_at,
           pt.name AS primary_tag_name
      FROM articles a
      LEFT JOIN LATERAL (
        SELECT t.name FROM article_tags at JOIN tags t ON t.id = at.tag_id
         WHERE at.article_id = a.id ORDER BY at.tag_id ASC LIMIT 1
      ) pt ON true
     WHERE a.status = 'published'
     ORDER BY a.published_at DESC NULLS LAST, a.id DESC
     LIMIT ${limit} OFFSET ${offset}
  `;
  return rows;
}

export async function countPublishedArticles() {
  const r = await sql`SELECT count(*)::int n FROM articles WHERE status = 'published'`;
  return r[0]?.n ?? 0;
}

// ---------------------------------------------------------------------------
// Publish: topic_draft -> articles
// ---------------------------------------------------------------------------

function esc(s) {
  return String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

// sections[] -> clean semantic HTML: <h2> per heading, <p> per paragraph. No
// inline styles, no legacy classes - the reader typography styles it.
export function sectionsToHtml(sections) {
  return (Array.isArray(sections) ? sections : []).map((s) => {
    const h = s.heading ? `<h2>${esc(s.heading)}</h2>` : '';
    const paras = String(s.body ?? '')
      .split(/\n\n+/)
      .map((p) => p.trim())
      .filter(Boolean)
      .map((p) => `<p>${esc(p)}</p>`)
      .join('\n');
    return [h, paras].filter(Boolean).join('\n');
  }).join('\n\n');
}

export function slugify(s) {
  return String(s ?? '')
    .toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 80) || 'article';
}

// Reserve a unique slug against existing articles (base, base-2, base-3, ...).
export async function uniqueArticleSlug(base) {
  const root = slugify(base);
  let slug = root;
  for (let n = 2; n < 100; n++) {
    const hit = await sql`SELECT 1 FROM articles WHERE slug = ${slug} LIMIT 1`;
    if (hit.length === 0) return slug;
    slug = `${root}-${n}`;
  }
  return `${root}-${Date.now()}`;
}
