import SiteHeaderServer from '@/components/SiteHeaderServer';
import SiteFooter from '@/components/SiteFooter';
import { getPublishedArticles, countPublishedArticles, deriveByline } from '@/lib/articleReader';
import './articles.css';

export const dynamic = 'force-dynamic';
export const metadata = { title: 'Articles - Sportsvyn', description: 'Published articles and features from Sportsvyn.' };

const PER_PAGE = 30;

function fmtDate(d) {
  if (!d) return '';
  return new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).toUpperCase().replace(',', '');
}

// Short provenance for the row byline strip.
function rowByline(a) {
  const b = deriveByline(a);
  if (b.kind === 'human') return b.label;
  if (b.kind === 'ai') return 'Sportsvyn · AI draft';
  return 'Generated by Sportsvyn';
}

export default async function ArticlesArchive({ searchParams }) {
  const sp = (await searchParams) ?? {};
  const page = Math.max(1, Number(sp.page) || 1);
  const offset = (page - 1) * PER_PAGE;

  const [rows, total] = await Promise.all([
    getPublishedArticles({ limit: PER_PAGE, offset }),
    countPublishedArticles(),
  ]);
  const pages = Math.max(1, Math.ceil(total / PER_PAGE));

  return (
    <>
      <SiteHeaderServer />
      <main className="arch-wrap">
        <header className="arch-head">
          <span className="arch-kicker">Sportsvyn</span>
          <h1 className="arch-title">Articles</h1>
          <p className="arch-sub">{total} published · newest first</p>
        </header>

        <div className="arch-list">
          {rows.length === 0 && <div className="arch-empty">No published articles yet.</div>}
          {rows.map((a) => {
            const isAuto = a.author === 'auto';
            const kicker = [a.primary_tag_name, a.type].filter(Boolean).join(' · ');
            return (
              <a key={a.id} className="arch-row" href={`/article/${a.slug}`}>
                <div className="arch-date">
                  <span className={`arch-marker${isAuto ? ' muted' : ''}`} aria-hidden="true" />
                  <span className="arch-date-txt">{fmtDate(a.published_at)}</span>
                </div>
                <div className="arch-content">
                  {kicker ? <span className="arch-row-kicker">{kicker}</span> : null}
                  <h2 className="arch-row-headline">{a.title}</h2>
                  {a.subtitle ? <p className="arch-row-dek">{a.subtitle}</p> : null}
                  <span className="arch-row-byline">{rowByline(a)}</span>
                </div>
                <span className="arch-arrow" aria-hidden="true">↗</span>
              </a>
            );
          })}
        </div>

        {pages > 1 && (
          <nav className="arch-pager">
            {page > 1 ? <a href={`/articles?page=${page - 1}`}>← Newer</a> : <span className="off">← Newer</span>}
            <span className="arch-pager-pos">Page {page} of {pages}</span>
            {page < pages ? <a href={`/articles?page=${page + 1}`}>Older →</a> : <span className="off">Older →</span>}
          </nav>
        )}
      </main>
      <SiteFooter />
    </>
  );
}
